# Generated by Django 4.0.1 on 2022-01-27 15:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 1, 27, 15, 27, 15, 623911, tzinfo=utc)),
        ),
    ]
