# Generated by Django 4.0.1 on 2022-01-27 15:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0002_alter_profile_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalProfile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='hospital')),
                ('Phone_Number', models.CharField(default='', max_length=14)),
                ('ESTD', models.DateField()),
                ('Date', models.DateField(default=datetime.datetime(2022, 1, 27, 15, 40, 47, 191830, tzinfo=utc))),
                ('Address', models.CharField(max_length=500)),
                ('Pan_Number', models.CharField(default='', max_length=100)),
                ('Remarks', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 1, 27, 15, 40, 47, 191830, tzinfo=utc)),
        ),
    ]
