# Generated by Django 4.0.1 on 2022-01-27 10:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='username')),
                ('Phone_Number', models.CharField(default='', max_length=14)),
                ('DOB', models.DateField()),
                ('Date', models.DateField(default=datetime.datetime(2022, 1, 27, 10, 3, 55, 712664, tzinfo=utc))),
                ('Address', models.CharField(max_length=500)),
                ('Profile_Picture', models.ImageField(upload_to='user_pics')),
                ('Remarks', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
